
server:
  port: 8002

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/


spring:
  application:
    name: microblog-admin-server
  security:
    user:
      name: admin
      password: admin