server:
  port: 8701
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: microblog-sms
  redis:
  #host地址
    host: 127.0.0.1
  #端口
    port: 6379
logging:
  level:
    com.microblog: debug

microblog:
  common:
    # 使能打印访问Url，在Controller方法上添加注解@PrintUrlAnno
    printUrlEnable: true
    # 使能打印方法执行耗时，在方法上添加注解@PrintUseTimeAnno
    printUseTimeEnable: true

rabbitmq:
  consumer:
    host: 127.0.0.1
    port: 5672
    name: lgj
    password: lgj

rocketmq:
  consumer:
    address: localhost:9816