server:
  port: 8000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

logging:
  level:
    com.cloud: debug
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: chat