
spring:
  application:
    name: microblog-admin-client
  boot:
    admin:
      client:
        url: http://localhost:8006
  security:
    user:
      name: admin
      password: admin
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8007

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/