
server:
  port: 8315
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.1:8001/eureka/

spring:
  application:
    name: microblog-consumer1

feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
