server:
  port: 9001

spring:
  application:
    name: microblog-config-server
  cloud:
    config:
      server:
      #  git:
       #   uri: https://github.com/lgjlife/micro-blog
          #Spring Cloud Config Server强制从远程存储库中提取
       #   force-pull: true
        #  search-paths: config-repo
        native:
          search-locations: file:config-repo
  profiles:
    active: native
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
