server:
  port: 9015

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: Microblog-Order
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
