server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

## gateway
spring:
  application:
    name: microblog-gateway
  cloud.gateway.routes:
    - id: microblog-auth
      uri: http://localhost:8000
      predicates:
        - Path=/api/auth/**
      filters:
        - StripPrefix=2
    - id: microblog-gateway
      uri: http://localhost:8010
      predicates:
        - Path=/api/gateway/**
      filters:
        - StripPrefix=2
    - id: api-keypair-route
      uri: http://localhost:8080
      predicates:
        - Path=/api/keypair/**
      filters:
        - StripPrefix=1
  security:
    user:
      password: password
      name: user
  security.oauth2.resourceserver.jwt.jwk-set-uri: 'http://localhost:8000/jwt/publickey'
logging:
  level:
    org: info
    com: error
    com.microblog: debug