server:
  port: 6003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  cloud:
    gateway:
      routes:
      # Normwal Websocket route
      - id: websocket_route
        uri: ws://localhost:8991
        predicates:
        - Path=/websocket/**
  application:
    name: gateway

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#zuul 路由配置
zuul:
  host:
    connect-timeout-millis: 7000
    socket-timeout-millis: 10000
  routes:
    #搜索系统
    microblog-search: /search/**
    # 微博系统
    microblog-blog: /blog/**
    # 用户模块
    microblog-user: /user/**
    # 积分系统
    microblog-points: /points/**
    # 任务系统
    microblog-scheduler: /scheduler/**
    microblog-center:
      path: /center/**
      serviceId: http://localhost:8001
   # users:
    #  path: /user/**
     # serviceId: microblog-user
  #  user:
   #   url: http://localhost:8002
      # serviceId: MICROBLOG-USER
    #  path: /user/**
    #需要忽略的头部信息，不在传播到其他服务
 #   sensitive-headers: Access-Control-Allow-Origin
  #  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

logging:
  level:
    org.springframework.security: debug
    com.microblog: debug
    org.apache.shiro.session.mgt: error
    org: debug

