server:
  port: 6003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: microblog-gateway
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#zuul 路由配置
zuul:
  host:
    connect-timeout-millis: 7000
    socket-timeout-millis: 10000
  routes:
    #搜索系统
    microblog-search: /search/**
    # 微博系统
    microblog-blog: /blog/**
    # 用户模块
    microblog-user: /user/**
    # 积分系统
    microblog-points: /points/**
    # 任务系统
    microblog-scheduler: /scheduler/**


   # users:
    #  path: /user/**
     # serviceId: microblog-user
  #  user:
   #   url: http://localhost:8002
      # serviceId: MICROBLOG-USER
    #  path: /user/**

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

logging:
  level:
    org.springframework.security: debug
    com.microblog: debug
    org.apache.shiro.session.mgt: error


