server:
  port: 8010
## gateway
spring:
  cloud.gateway.routes:
    - id: microblog-auth
      uri: http://localhost:8000
      predicates:
        - Path=/api/auth/**
      filters:
        - StripPrefix=2
    - id: api-keypair-route
      uri: http://localhost:8080
      predicates:
        - Path=/api/keypair/**
      filters:
        - StripPrefix=1
  security:
    user:
      password: password
      name: user
  security.oauth2.resourceserver.jwt.jwk-set-uri: 'http://localhost:8000/jwt/publickey'
logging:
  level:
    org: debug
    com: error
    com.microblog: debug