server:
  port: 8700


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300,127.0.0.1:9301
  application:
    name: microblog-search

logging:
  level:
    com.clolud.microblog: debug
    org.apache: error

microblog:
  common:
    # 使能打印访问Url，在Controller方法上添加注解@PrintUrlAnno
    printUrlEnable: true
    # 使能打印方法执行耗时，在方法上添加注解@PrintUseTimeAnno
    printUseTimeEnable: true

swagger:
  basePackage: com.microblog.scheduler.web.controller
  title: "Blog API 文档"
  contactName: "lgj"
  contactUrl: contactUrl-demo
  contactEmail: contactEmail-demo
  version: v1.0.0
  description: blog
  termsOfServiceUrl: termsOfServiceUrl-demo
  license: license-demo
  licenseUrl: licenseUrl-demo